# Generated by Django 5.0.6 on 2024-05-24 18:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Contenido'),
        ),
    ]
